//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="amqp://biztalkadapter.ampq/2018/Types")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="amqp://biztalkadapter.ampq/2018/Types", IsNullable=false)]
public partial class ReceiveMessage {
    
    private string consumerTagField;
    
    private ulong deliveryTagField;
    
    private bool deliveryTagFieldSpecified;
    
    private bool redeliveredField;
    
    private bool redeliveredFieldSpecified;
    
    private string exchangeField;
    
    private string routingKeyField;
    
    private string bodyField;
    
    private BasicProperties basicPropertiesField;
    
    /// <remarks/>
    public string ConsumerTag {
        get {
            return this.consumerTagField;
        }
        set {
            this.consumerTagField = value;
        }
    }
    
    /// <remarks/>
    public ulong DeliveryTag {
        get {
            return this.deliveryTagField;
        }
        set {
            this.deliveryTagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeliveryTagSpecified {
        get {
            return this.deliveryTagFieldSpecified;
        }
        set {
            this.deliveryTagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool Redelivered {
        get {
            return this.redeliveredField;
        }
        set {
            this.redeliveredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RedeliveredSpecified {
        get {
            return this.redeliveredFieldSpecified;
        }
        set {
            this.redeliveredFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Exchange {
        get {
            return this.exchangeField;
        }
        set {
            this.exchangeField = value;
        }
    }
    
    /// <remarks/>
    public string RoutingKey {
        get {
            return this.routingKeyField;
        }
        set {
            this.routingKeyField = value;
        }
    }
    
    /// <remarks/>
    public string Body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
    
    /// <remarks/>
    public BasicProperties BasicProperties {
        get {
            return this.basicPropertiesField;
        }
        set {
            this.basicPropertiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="amqp://biztalkadapter.ampq/2018/Types")]
public partial class BasicProperties {
    
    private string contentTypeField;
    
    private string contentEncodingField;
    
    private byte deliveryModeField;
    
    private bool deliveryModeFieldSpecified;
    
    private byte priorityField;
    
    private bool priorityFieldSpecified;
    
    private string correlationIdField;
    
    private string replyToField;
    
    private string expirationField;
    
    private string messageIdField;
    
    private string typeField;
    
    private string userIdField;
    
    private string appIdField;
    
    private string clusterIdField;
    
    private long timestampField;
    
    private bool timestampFieldSpecified;
    
    private int protocolClassIdField;
    
    private bool protocolClassIdFieldSpecified;
    
    private string protocolClassNameField;
    
    private BasicPropertiesItem[] headersField;
    
    /// <remarks/>
    public string ContentType {
        get {
            return this.contentTypeField;
        }
        set {
            this.contentTypeField = value;
        }
    }
    
    /// <remarks/>
    public string ContentEncoding {
        get {
            return this.contentEncodingField;
        }
        set {
            this.contentEncodingField = value;
        }
    }
    
    /// <remarks/>
    public byte DeliveryMode {
        get {
            return this.deliveryModeField;
        }
        set {
            this.deliveryModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeliveryModeSpecified {
        get {
            return this.deliveryModeFieldSpecified;
        }
        set {
            this.deliveryModeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrioritySpecified {
        get {
            return this.priorityFieldSpecified;
        }
        set {
            this.priorityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string CorrelationId {
        get {
            return this.correlationIdField;
        }
        set {
            this.correlationIdField = value;
        }
    }
    
    /// <remarks/>
    public string ReplyTo {
        get {
            return this.replyToField;
        }
        set {
            this.replyToField = value;
        }
    }
    
    /// <remarks/>
    public string Expiration {
        get {
            return this.expirationField;
        }
        set {
            this.expirationField = value;
        }
    }
    
    /// <remarks/>
    public string MessageId {
        get {
            return this.messageIdField;
        }
        set {
            this.messageIdField = value;
        }
    }
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    public string AppId {
        get {
            return this.appIdField;
        }
        set {
            this.appIdField = value;
        }
    }
    
    /// <remarks/>
    public string ClusterId {
        get {
            return this.clusterIdField;
        }
        set {
            this.clusterIdField = value;
        }
    }
    
    /// <remarks/>
    public long Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int ProtocolClassId {
        get {
            return this.protocolClassIdField;
        }
        set {
            this.protocolClassIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ProtocolClassIdSpecified {
        get {
            return this.protocolClassIdFieldSpecified;
        }
        set {
            this.protocolClassIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ProtocolClassName {
        get {
            return this.protocolClassNameField;
        }
        set {
            this.protocolClassNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable=false)]
    public BasicPropertiesItem[] Headers {
        get {
            return this.headersField;
        }
        set {
            this.headersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="amqp://biztalkadapter.ampq/2018/Types")]
public partial class BasicPropertiesItem {
    
    private string keyField;
    
    private string valueField;
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="amqp://biztalkadapter.ampq/2018/Types")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="amqp://biztalkadapter.ampq/2018/Types", IsNullable=false)]
public partial class SendMessageRequest {
    
    private string routingKeyField;
    
    private string bodyField;
    
    private BasicProperties basicPropertiesField;
    
    /// <remarks/>
    public string RoutingKey {
        get {
            return this.routingKeyField;
        }
        set {
            this.routingKeyField = value;
        }
    }
    
    /// <remarks/>
    public string Body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
    
    /// <remarks/>
    public BasicProperties BasicProperties {
        get {
            return this.basicPropertiesField;
        }
        set {
            this.basicPropertiesField = value;
        }
    }
}
